name: Build and Deploy

on:
  push:
    branches:
      - master  # Change this to your primary branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # This checks out your code from the GitHub repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify your Node.js version

      - name: Install Dependencies
        run: npm install  # Install all dependencies

      - name: Build Application
        run: npm run build  # Build your application (make sure to define this script in package.json)

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after the 'build' job finishes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7  # Uses SSH Action to connect to your server
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            echo "Deploying application..."

            # Navigate to your project directory
            cd /path/to/your/project  # Change this to your actual project directory on the server

            # Pull the latest changes from the repository
            git pull origin master

            # Install dependencies
            npm install

            # Build the application
            npm run build

            # Start the application (ensure this runs in the background or as a service)
            npm run start &  # Adjust the start command if needed for your setup

      - name: Clean up Background Processes
        run: |
          pkill -f "npm run start" || true
          echo "Cleaned up any existing background processes"

      - name: Restart Application
        run: |
          nohup npm run start &
          echo "Application restarted successfully"
