name: Frontend Build and Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a dummy command
      run: echo "Dummy Docker Image Build & Push Command"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

  

    - name: SSH into server and pull latest Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: |
          sudo docker pull louislam/uptime-kuma:1
          sudo docker stop uptime-kuma || true
          sudo docker rm uptime-kuma || true
          sudo docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma --pull always louislam/uptime-kuma:1
