name: Build and Deploy

on:
  push:
    branches:
      - master  # Adjust to your main branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            echo "Deploying application..."
            # Install Node.js and npm if not already installed
            sudo apt update
            sudo apt install -y nodejs npm

            # Define the project directory
            PROJECT_DIR="/home/ubuntu/uptime-kuma"
            # Clone the repository if it does not exist
            if [ ! -d "$PROJECT_DIR" ]; then
              git clone https://github.com/Maram-Hassan/uptime-kuma.git $PROJECT_DIR
            fi
            cd $PROJECT_DIR
            
            # Pull the latest changes from the repository
            git pull origin master
            # Run the specified npm commands
            npm cache clean --force
            npm install
            npm install dayjs
            NODE_OPTIONS="--max-old-space-size=4096" npm run build  # Allocating 4GB of memory
            npm run start  # Ensure that this line runs the correct start command
