name: Build and Deploy

on:
  push:
    branches:
      - master  # Trigger the workflow when pushing to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out your code from the GitHub repository

      - name: Build Step
        run: |
          echo "Building..."
          PROJECT_DIR="/home/ubuntu/uptime-kuma"
          npm install  # Install dependencies
          npm run build  # Build the application

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after the 'build' job finishes

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7  # Uses SSH Action to connect to your server
        with:
          host: ${{ secrets.SERVER_HOST }}  # Your server's IP or domain
          username: ubuntu  # Your server username
          key: ${{ secrets.SERVER_KEY }}  # Your private SSH key (ensure it's stored in GitHub secrets)
          port: 22
          script: |
            echo "Deploying application..."

            # Install Node.js and npm (if not already installed)
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -  # Setup Node.js 18.x
            sudo apt-get install -y nodejs

            # Verify Node.js and npm are installed
            node -v
            npm -v

            # Navigate to the project directory
            cd $PROJECT_DIR
            # Pull the latest changes from the repository
            git pull origin master

            # Install dependencies
            npm install

            # Build the application
            npm run build

            # Start the application (use pm2 for production, or npm run start)
            npm run start &  # Or use pm2 to start the application persistently
